type GravityType =
  | 'None'
  | 'Center'
  | 'East'
  | 'Forget'
  | 'NorthEast'
  | 'North'
  | 'NorthWest'
  | 'SouthEast'
  | 'South'
  | 'SouthWest'
  | 'West'
type FilterType =
  | 'Bartlett'
  | 'Blackman'
  | 'Bohman'
  | 'Box'
  | 'Catrom'
  | 'Cosine'
  | 'Cubic'
  | 'Gaussian'
  | 'Hamming'
  | 'Hann'
  | 'Hermite'
  | 'Jinc'
  | 'Kaiser'
  | 'Lagrange'
  | 'Lanczos'
  | 'Lanczos2'
  | 'Lanczos2Sharp'
  | 'LanczosRadius'
  | 'LanczosSharp'
  | 'Mitchell'
  | 'Parzen'
  | 'Point'
  | 'Quadratic'
  | 'Robidoux'
  | 'RobidouxSharp'
  | 'Sinc'
  | 'SincFast'
  | 'Spline'
  | 'CubicSpline'
  | 'Triangle'
  | 'Welch'
type InterpolateType =
  | 'Average'
  | 'Average4'
  | 'Average9'
  | 'Average16'
  | 'Background'
  | 'Bilinear'
  | 'Blend'
  | 'Catrom'
  | 'Integer'
  | 'Mesh'
  | 'Nearest'
  | 'Spline'
type AlphaType =
  | 'Activate'
  | 'Associate'
  | 'Background'
  | 'Copy'
  | 'Deactivate'
  | 'Discrete'
  | 'Disassociate'
  | 'Extract'
  | 'Off'
  | 'On'
  | 'Opaque'
  | 'Remove'
  | 'Set'
  | 'Shape'
  | 'Transparent'
type ComposeType =
  | 'Atop'
  | 'Blend'
  | 'Blur'
  | 'Bumpmap'
  | 'ChangeMask'
  | 'Clear'
  | 'ColorBurn'
  | 'ColorDodge'
  | 'Colorize'
  | 'CopyAlpha'
  | 'CopyBlack'
  | 'CopyBlue'
  | 'Copy'
  | 'CopyCyan'
  | 'CopyGreen'
  | 'CopyMagenta'
  | 'CopyRed'
  | 'CopyYellow'
  | 'Darken'
  | 'DarkenIntensity'
  | 'Difference'
  | 'Displace'
  | 'Dissolve'
  | 'Distort'
  | 'DivideDst'
  | 'DivideSrc'
  | 'DstAtop'
  | 'Dst'
  | 'DstIn'
  | 'DstOut'
  | 'DstOver'
  | 'Exclusion'
  | 'Freeze'
  | 'HardLight'
  | 'HardMix'
  | 'Hue'
  | 'In'
  | 'Intensity'
  | 'Interpolate'
  | 'LightenIntensity'
  | 'Lighten'
  | 'LinearBurn'
  | 'LinearDodge'
  | 'LinearLight'
  | 'Luminize'
  | 'Mathematics'
  | 'MinusDst'
  | 'MinusSrc'
  | 'Modulate'
  | 'ModulusAdd'
  | 'ModulusSubtract'
  | 'Multiply'
  | 'Negate'
  | 'None'
  | 'Out'
  | 'Overlay'
  | 'Over'
  | 'PegtopLight'
  | 'PinLight'
  | 'Plus'
  | 'Reflect'
  | 'Replace'
  | 'RMSE'
  | 'Saturate'
  | 'Screen'
  | 'SoftBurn'
  | 'SoftDodge'
  | 'SoftLight'
  | 'SrcAtop'
  | 'SrcIn'
  | 'SrcOut'
  | 'SrcOver'
  | 'Src'
  | 'Stamp'
  | 'Stereo'
  | 'VividLight'
  | 'Xor'
type DirectionType = 'left-to-right' | 'right-to-left'
type DisposeType = 'Background' | 'None' | 'Previous'
type DistortType =
  | 'Affine'
  | 'AffineProjection'
  | 'Arc'
  | 'Barrel'
  | 'BilinearForward'
  | 'BilinearReverse'
  | 'DePolar'
  | 'Perspective'
  | 'PerspectiveProjection'
  | 'Polar'
  | 'Polynomial'
  | 'Resize'
  | 'Rotate'
  | 'ScaleRotateTranslate'
  | 'Shepards'
type DitherType = 'FloydSteinberg' | 'Riemersma' | 'None'
type DebugType =
  | 'All'
  | 'Accelerate'
  | 'Annotate'
  | 'Blob'
  | 'Cache'
  | 'Coder'
  | 'Configure'
  | 'Deprecate'
  | 'Exception'
  | 'Locale'
  | 'None'
  | 'Render'
  | 'Resource'
  | 'Security'
  | 'TemporaryFile'
  | 'Trace'
  | 'Transform'
  | 'User'
  | 'X11'
type ColorspaceType =
  | 'CMY'
  | 'CMYK'
  | 'Gray'
  | 'HCL'
  | 'HCLp'
  | 'HSB'
  | 'HSI'
  | 'HSL'
  | 'HSV'
  | 'HWB'
  | 'Lab'
  | 'LCH'
  | 'LCHab'
  | 'LCHuv'
  | 'LMS'
  | 'Log'
  | 'Luv'
  | 'OHTA'
  | 'Rec601YCbCr'
  | 'Rec709YCbCr'
  | 'RGB'
  | 'scRGB'
  | 'sRGB'
  | 'Transparent'
  | 'XYZ'
  | 'YCbCr'
  | 'YCC'
  | 'YDbDr'
  | 'YIQ'
  | 'YPbPr'
  | 'YUV'
type CompressType =
  | 'B44'
  | 'B44A'
  | 'BZip'
  | 'DXT1'
  | 'DXT3'
  | 'DXT5'
  | 'Fax'
  | 'Group4'
  | 'JBIG1'
  | 'JBIG2'
  | 'JPEG'
  | 'JPEG2000'
  | 'Lossless'
  | 'LosslessJPEG'
  | 'LZMA'
  | 'LZW'
  | 'None'
  | 'Piz'
  | 'Pxr24'
  | 'RLE'
  | 'Zip'
  | 'ZipS'
type ChannelType =
  | 'Red'
  | 'Green'
  | 'Blue'
  | 'Alpha'
  | 'Gray'
  | 'Cyan'
  | 'Magenta'
  | 'Yellow'
  | 'Black'
  | 'Opacity'
  | 'Index'
  | 'RGB'
  | 'RGBA'
  | 'CMYK'
  | 'CMYKA'
  | number
type GrayscaleType = 'average' | 'brightness' | 'lightness' | 'luma' | 'rec601luma' | 'rec709luma' | 'rms'
type EndianType = 'LSB' | 'MSB'
type EvaluateType =
  | 'Add'
  | 'AddModulus'
  | 'And'
  | 'Cos'
  | 'Cosine'
  | 'Divide'
  | 'Exp'
  | 'Gaussian'
  | 'LeftShift'
  | 'Log'
  | 'Max'
  | 'Mean'
  | 'Median'
  | 'Min'
  | 'Multiply'
  | 'Or'
  | 'Pow'
  | 'RightShift'
  | 'RMS'
  | 'Set'
  | 'Sin'
  | 'Sine'
  | 'Subtract'
  | 'Sum'
  | 'Threshold'
  | 'ThresholdBlack'
  | 'ThresholdWhite'
  | 'Uniform'
  | 'Xor'
type FunctionType = 'Polynomial' | 'Sinusoid' | 'ArcSin' | 'ArcTan'
type IntentType = 'Absolute' | 'Perceptual' | 'Relative' | 'Saturation'
type InterlaceType = 'Line' | 'None' | 'Plane' | 'Partition' | 'JPEG' | 'GIF' | 'PNG'
type LayersType =
  | 'coalesce'
  | 'compare-any'
  | 'compare-clear'
  | 'compare-overlay'
  | 'composite'
  | 'dispose'
  | 'flatten'
  | 'merge'
  | 'mosaic'
  | 'optimize'
  | 'optimize-frame'
  | 'optimize-plus'
  | 'optimize-trans'
  | 'remove-dups'
  | 'remove-zero'
type LimitType = 'disk' | 'file' | 'map' | 'memory' | 'thread' | 'throttle' | 'time'
type MorphologyType =
  | 'Convolve'
  | 'Correlate'
  | 'Erode'
  | 'Dilate'
  | 'ErodeIntensity'
  | 'DilateIntensity'
  | 'Distance'
  | 'Open'
  | 'Close'
  | 'OpenIntensity'
  | 'CloseIntensity'
  | 'Smooth'
  | 'EdgeIn'
  | 'EdgeOut'
  | 'Edge'
  | 'TopHat'
  | 'BottomHat'
  | 'HitAndMiss'
  | 'Thinning'
  | 'Thicken'
type NoiseType = 'Gaussian' | 'Impulse' | 'Laplacian' | 'Multiplicative' | 'Poisson' | 'Random' | 'Uniform'
type OrientType =
  | 'TopLeft'
  | 'TopRight'
  | 'BottomRight'
  | 'BottomLeft'
  | 'LeftTop'
  | 'RightTop'
  | 'RightBottom'
  | 'LeftBottom'
type PreviewType =
  | 'Rotate'
  | 'Roll'
  | 'Hue'
  | 'Saturation'
  | 'Brightness'
  | 'Gamma'
  | 'Spiff'
  | 'Dull'
  | 'Grayscale'
  | 'Quantize'
  | 'Despeckle'
  | 'ReduceNoise'
  | 'AddNoise'
  | 'Sharpen'
  | 'Blur'
  | 'Threshold'
  | 'EdgeDetect'
  | 'Spread'
  | 'Solarize'
  | 'Shade'
  | 'Raise'
  | 'Segment'
  | 'Swirl'
  | 'Implode'
  | 'Wave'
  | 'OilPaint'
  | 'Charcoal'
  | 'JPEG'
type StatisticType =
  | 'Gradient'
  | 'Maximum'
  | 'Mean'
  | 'Median'
  | 'Minimum'
  | 'Mode'
  | 'Nonpeak'
  | 'RootMeanSquare'
  | 'StandardDeviation'
type StretchType =
  | 'Any'
  | 'Condensed'
  | 'Expanded'
  | 'ExtraCondensed'
  | 'ExtraExpanded'
  | 'Normal'
  | 'SemiCondensed'
  | 'SemiExpanded'
  | 'UltraCondensed'
  | 'UltraExpanded'
type StyleType = 'Any' | 'Italic' | 'Normal' | 'Oblique'
type VirtualPixelType =
  | 'Background'
  | 'Black'
  | 'CheckerTile'
  | 'Dither'
  | 'Edge'
  | 'Gray'
  | 'HorizontalTile'
  | 'HorizontalTileEdge'
  | 'Mirror'
  | 'None'
  | 'Random'
  | 'Tile'
  | 'Transparent'
  | 'VerticalTile'
  | 'VerticalTileEdge'
  | 'White'
type IlluminantType = 'A' | 'B' | 'C' | 'D50' | 'D55' | 'D65' | 'D75' | 'E' | 'F2' | 'F7' | 'F11'
type IntensityType = 'Average' | 'Brightness' | 'Lightness' | 'Luma' | 'MS' | 'Rec601Luma' | 'Rec709Luma' | 'RMS'
type AutoThresholdType = 'OTSU' | 'Kapur' | 'Triangle'
type SparseColorMethodType = 'Barycentric' | 'Bilinear' | 'Polynomial' | 'Shepards' | 'Voronoi'
type ComplexOperatorType = 'Add' | 'Conjugate' | 'Divide' | 'MagnitudePhase' | 'Multiply' | 'RealImaginary' | 'Subtract'
type ListType =
  | 'Color'
  | 'Configure'
  | 'Delegate'
  | 'Font'
  | 'Format'
  | 'Locale'
  | 'Log'
  | 'Magic'
  | 'Module'
  | 'Policy'
  | 'Resource'
  | 'Threshold'
  | 'Type'
type NumberOrPercent = number | `${number}%`

export type {
  AlphaType,
  AutoThresholdType,
  ChannelType,
  ColorspaceType,
  ComplexOperatorType,
  ComposeType,
  CompressType,
  DebugType,
  DirectionType,
  DisposeType,
  DistortType,
  DitherType,
  EndianType,
  EvaluateType,
  FilterType,
  FunctionType,
  GravityType,
  GrayscaleType,
  IlluminantType,
  IntensityType,
  IntentType,
  InterlaceType,
  InterpolateType,
  LayersType,
  LimitType,
  ListType,
  MorphologyType,
  NoiseType,
  NumberOrPercent,
  OrientType,
  PreviewType,
  SparseColorMethodType,
  StatisticType,
  StretchType,
  StyleType,
  VirtualPixelType,
}
