type GravityType =
  | 'None'
  | 'Center'
  | 'East'
  | 'Forget'
  | 'NorthEast'
  | 'North'
  | 'NorthWest'
  | 'SouthEast'
  | 'South'
  | 'SouthWest'
  | 'West'
type FilterType =
  | 'Bartlett'
  | 'Blackman'
  | 'Bohman'
  | 'Box'
  | 'Catrom'
  | 'Cosine'
  | 'Cubic'
  | 'Gaussian'
  | 'Hamming'
  | 'Hann'
  | 'Hermite'
  | 'Jinc'
  | 'Kaiser'
  | 'Lagrange'
  | 'Lanczos'
  | 'Lanczos2'
  | 'Lanczos2Sharp'
  | 'LanczosRadius'
  | 'LanczosSharp'
  | 'MagicKernelSharp2013'
  | 'MagicKernelSharp2021'
  | 'Mitchell'
  | 'Parzen'
  | 'Point'
  | 'Quadratic'
  | 'Robidoux'
  | 'RobidouxSharp'
  | 'Sinc'
  | 'SincFast'
  | 'Spline'
  | 'CubicSpline'
  | 'Triangle'
  | 'Welch'
type InterpolateType =
  | 'Average'
  | 'Average4'
  | 'Average9'
  | 'Average16'
  | 'Background'
  | 'Bilinear'
  | 'Blend'
  | 'Catrom'
  | 'Integer'
  | 'Mesh'
  | 'Nearest'
  | 'Spline'
type AlphaType =
  | 'Activate'
  | 'Associate'
  | 'Background'
  | 'Copy'
  | 'Deactivate'
  | 'Discrete'
  | 'Disassociate'
  | 'Extract'
  | 'Off'
  | 'OffIfOpaque'
  | 'On'
  | 'Opaque'
  | 'Remove'
  | 'Set'
  | 'Shape'
  | 'Transparent'
type ComposeType =
  | 'Atop'
  | 'Blend'
  | 'Blur'
  | 'Bumpmap'
  | 'ChangeMask'
  | 'Clear'
  | 'ColorBurn'
  | 'ColorDodge'
  | 'Colorize'
  | 'CopyAlpha'
  | 'CopyBlack'
  | 'CopyBlue'
  | 'Copy'
  | 'CopyCyan'
  | 'CopyGreen'
  | 'CopyMagenta'
  | 'CopyRed'
  | 'CopyYellow'
  | 'Darken'
  | 'DarkenIntensity'
  | 'Difference'
  | 'Displace'
  | 'Dissolve'
  | 'Distort'
  | 'DivideDst'
  | 'DivideSrc'
  | 'DstAtop'
  | 'Dst'
  | 'DstIn'
  | 'DstOut'
  | 'DstOver'
  | 'Exclusion'
  | 'Freeze'
  | 'HardLight'
  | 'HardMix'
  | 'Hue'
  | 'In'
  | 'Intensity'
  | 'Interpolate'
  | 'LightenIntensity'
  | 'Lighten'
  | 'LinearBurn'
  | 'LinearDodge'
  | 'LinearLight'
  | 'Luminize'
  | 'Mathematics'
  | 'MinusDst'
  | 'MinusSrc'
  | 'Modulate'
  | 'ModulusAdd'
  | 'ModulusSubtract'
  | 'Multiply'
  | 'Negate'
  | 'None'
  | 'Out'
  | 'Overlay'
  | 'Over'
  | 'PegtopLight'
  | 'PinLight'
  | 'Plus'
  | 'Reflect'
  | 'Replace'
  | 'RMSE'
  | 'SaliencyBlend'
  | 'Saturate'
  | 'Screen'
  | 'SeamlessBlend'
  | 'SoftBurn'
  | 'SoftDodge'
  | 'SoftLight'
  | 'SrcAtop'
  | 'SrcIn'
  | 'SrcOut'
  | 'SrcOver'
  | 'Src'
  | 'Stamp'
  | 'Stereo'
  | 'VividLight'
  | 'Xor'
type DirectionType = 'left-to-right' | 'right-to-left' | 'top-to-bottom'
type DisposeType = 'Background' | 'None' | 'Previous'
type DistortType =
  | 'Affine'
  | 'AffineProjection'
  | 'Arc'
  | 'Barrel'
  | 'BarrelInverse'
  | 'BilinearForward'
  | 'BilinearReverse'
  | 'DePolar'
  | 'Perspective'
  | 'PerspectiveProjection'
  | 'Polar'
  | 'Polynomial'
  | 'Resize'
  | 'RigidAffine'
  | 'ScaleRotateTranslate'
  | 'Shepards'
  | 'SRT'
type DitherType = 'FloydSteinberg' | 'Riemersma' | 'None'
type DebugType =
  | 'All'
  | 'Accelerate'
  | 'Annotate'
  | 'Blob'
  | 'Cache'
  | 'Coder'
  | 'Command'
  | 'Configure'
  | 'Deprecate'
  | 'Draw'
  | 'Exception'
  | 'Locale'
  | 'Module'
  | 'None'
  | 'Pixel'
  | 'Policy'
  | 'Resource'
  | 'Trace'
  | 'Transform'
  | 'User'
  | 'Wand'
  | 'X11'
type ColorspaceType =
  | 'Adobe98'
  | 'CAT02LMS'
  | 'CIELab'
  | 'CMY'
  | 'CMYK'
  | 'DisplayP3'
  | 'Gray'
  | 'HCL'
  | 'HCLp'
  | 'HSB'
  | 'HSI'
  | 'HSL'
  | 'HSV'
  | 'HWB'
  | 'Jzazbz'
  | 'Lab'
  | 'LCH'
  | 'LCHab'
  | 'LCHuv'
  | 'LinearGray'
  | 'LMS'
  | 'Log'
  | 'Luv'
  | 'OHTA'
  | 'Oklab'
  | 'Oklch'
  | 'ProPhoto'
  | 'Rec601YCbCr'
  | 'Rec709YCbCr'
  | 'RGB'
  | 'scRGB'
  | 'sRGB'
  | 'Transparent'
  | 'xyY'
  | 'XYZ'
  | 'YCbCr'
  | 'YCC'
  | 'YDbDr'
  | 'YIQ'
  | 'YPbPr'
  | 'YUV'
type CompressType =
  | 'B44'
  | 'B44A'
  | 'BC7'
  | 'BZip'
  | 'DXT1'
  | 'DXT3'
  | 'DXT5'
  | 'DWAA'
  | 'DWAB'
  | 'Fax'
  | 'Group4'
  | 'JBIG1'
  | 'JBIG2'
  | 'JPEG'
  | 'JPEG2000'
  | 'LERC'
  | 'Lossless'
  | 'LosslessJPEG'
  | 'LZMA'
  | 'LZW'
  | 'None'
  | 'Piz'
  | 'Pxr24'
  | 'RLE'
  | 'RunlengthEncoded'
  | 'WebP'
  | 'Zip'
  | 'ZipS'
  | 'Zstd'
type ChannelType =
  | 'Red'
  | 'Green'
  | 'Blue'
  | 'Alpha'
  | 'Gray'
  | 'Cyan'
  | 'Magenta'
  | 'Yellow'
  | 'Black'
  | 'All'
  | 'Sync'
  | 'RGB'
  | 'RGBA'
  | 'CMYK'
  | 'CMYKA'
  | number
type GrayscaleType =
  | 'average'
  | 'brightness'
  | 'lightness'
  | 'mean'
  | 'ms'
  | 'rec601luma'
  | 'rec601luminance'
  | 'rec709luma'
  | 'rec709luminance'
  | 'rms'
type EndianType = 'LSB' | 'MSB'
type EvaluateType =
  | 'Abs'
  | 'Add'
  | 'AddModulus'
  | 'And'
  | 'Cos'
  | 'Cosine'
  | 'Divide'
  | 'Exp'
  | 'Exponential'
  | 'GaussianNoise'
  | 'ImpulseNoise'
  | 'InverseLog'
  | 'LaplacianNoise'
  | 'LeftShift'
  | 'Log'
  | 'Max'
  | 'Mean'
  | 'Median'
  | 'Min'
  | 'Multiply'
  | 'MultiplicativeNoise'
  | 'Or'
  | 'PoissonNoise'
  | 'Pow'
  | 'RightShift'
  | 'RMS'
  | 'RootMeanSquare'
  | 'Set'
  | 'Sin'
  | 'Sine'
  | 'Subtract'
  | 'Sum'
  | 'Threshold'
  | 'ThresholdBlack'
  | 'ThresholdWhite'
  | 'UniformNoise'
  | 'Xor'
type FunctionType = 'Polynomial' | 'Sinusoid' | 'ArcSin' | 'ArcTan'
type IntentType = 'Absolute' | 'Perceptual' | 'Relative' | 'Saturation'
type InterlaceType = 'Line' | 'None' | 'Plane' | 'Partition' | 'JPEG' | 'GIF' | 'PNG'
type LayersType =
  | 'coalesce'
  | 'compare-any'
  | 'compare-clear'
  | 'compare-overlay'
  | 'composite'
  | 'dispose'
  | 'flatten'
  | 'merge'
  | 'mosaic'
  | 'optimize'
  | 'optimize-frame'
  | 'optimize-plus'
  | 'optimize-transparency'
  | 'remove-dups'
  | 'remove-zero'
  | 'trim-bounds'
type LimitType =
  | 'area'
  | 'disk'
  | 'file'
  | 'height'
  | 'list-length'
  | 'map'
  | 'memory'
  | 'thread'
  | 'throttle'
  | 'time'
  | 'width'
type MorphologyType =
  | 'Convolve'
  | 'Correlate'
  | 'Erode'
  | 'Dilate'
  | 'ErodeIntensity'
  | 'DilateIntensity'
  | 'Distance'
  | 'IterativeDistance'
  | 'Open'
  | 'Close'
  | 'OpenIntensity'
  | 'CloseIntensity'
  | 'Smooth'
  | 'EdgeIn'
  | 'EdgeOut'
  | 'Edge'
  | 'TopHat'
  | 'BottomHat'
  | 'HitAndMiss'
  | 'Thinning'
  | 'Thicken'
type NoiseType = 'Gaussian' | 'Impulse' | 'Laplacian' | 'Multiplicative' | 'Poisson' | 'Random' | 'Uniform'
type OrientType =
  | 'TopLeft'
  | 'TopRight'
  | 'BottomRight'
  | 'BottomLeft'
  | 'LeftTop'
  | 'RightTop'
  | 'RightBottom'
  | 'LeftBottom'
type PreviewType =
  | 'Rotate'
  | 'Roll'
  | 'Hue'
  | 'Saturation'
  | 'Brightness'
  | 'Gamma'
  | 'Spiff'
  | 'Dull'
  | 'Grayscale'
  | 'Quantize'
  | 'Despeckle'
  | 'ReduceNoise'
  | 'AddNoise'
  | 'Sharpen'
  | 'Blur'
  | 'Threshold'
  | 'EdgeDetect'
  | 'Spread'
  | 'Solarize'
  | 'Shade'
  | 'Shear'
  | 'Raise'
  | 'Segment'
  | 'Swirl'
  | 'Implode'
  | 'Wave'
  | 'OilPaint'
  | 'Charcoal'
  | 'JPEG'
type StatisticType =
  | 'Contrast'
  | 'Gradient'
  | 'Maximum'
  | 'Mean'
  | 'Median'
  | 'Minimum'
  | 'Mode'
  | 'NonPeak'
  | 'RMS'
  | 'RootMeanSquare'
  | 'StandardDeviation'
type StretchType =
  | 'Any'
  | 'Condensed'
  | 'Expanded'
  | 'ExtraCondensed'
  | 'ExtraExpanded'
  | 'Normal'
  | 'SemiCondensed'
  | 'SemiExpanded'
  | 'UltraCondensed'
  | 'UltraExpanded'
type StyleType = 'Any' | 'Italic' | 'Normal' | 'Oblique'
type VirtualPixelType =
  | 'Background'
  | 'Black'
  | 'CheckerTile'
  | 'Dither'
  | 'Edge'
  | 'Gray'
  | 'HorizontalTile'
  | 'HorizontalTileEdge'
  | 'Mirror'
  | 'None'
  | 'Random'
  | 'Tile'
  | 'Transparent'
  | 'VerticalTile'
  | 'VerticalTileEdge'
  | 'White'
type IlluminantType = 'A' | 'B' | 'C' | 'D50' | 'D55' | 'D65' | 'D75' | 'E' | 'F2' | 'F7' | 'F11'
type IntensityType =
  | 'Average'
  | 'Brightness'
  | 'Lightness'
  | 'Mean'
  | 'MS'
  | 'Rec601Luma'
  | 'Rec601Luminance'
  | 'Rec709Luma'
  | 'Rec709Luminance'
  | 'RMS'
type AutoThresholdType = 'OTSU' | 'Kapur' | 'Triangle'
type SparseColorMethodType = 'Barycentric' | 'Bilinear' | 'Inverse' | 'Manhattan' | 'Shepards' | 'Voronoi'
type ComplexOperatorType = 'Add' | 'Conjugate' | 'Divide' | 'MagnitudePhase' | 'Multiply' | 'RealImaginary' | 'Subtract'
type ListType =
  | 'Align'
  | 'Alpha'
  | 'AutoThreshold'
  | 'Boolean'
  | 'Cache'
  | 'Channel'
  | 'Class'
  | 'CLI'
  | 'ClipPath'
  | 'Coder'
  | 'Color'
  | 'Colorspace'
  | 'Command'
  | 'Compliance'
  | 'Complex'
  | 'Compose'
  | 'Compress'
  | 'Configure'
  | 'DataType'
  | 'Debug'
  | 'Decoration'
  | 'Delegate'
  | 'Direction'
  | 'Dispose'
  | 'Distort'
  | 'Dither'
  | 'Endian'
  | 'Evaluate'
  | 'FillRule'
  | 'Filter'
  | 'Font'
  | 'Format'
  | 'Function'
  | 'Gradient'
  | 'Gravity'
  | 'Illuminant'
  | 'Intensity'
  | 'Intent'
  | 'Interlace'
  | 'Interpolate'
  | 'Kernel'
  | 'Layers'
  | 'LineCap'
  | 'LineJoin'
  | 'List'
  | 'Locale'
  | 'LogEvent'
  | 'Log'
  | 'Magic'
  | 'Method'
  | 'Metric'
  | 'Mime'
  | 'Mode'
  | 'Morphology'
  | 'Module'
  | 'Noise'
  | 'Orientation'
  | 'Pagesize'
  | 'PixelChannel'
  | 'PixelIntensity'
  | 'PixelMask'
  | 'PixelTrait'
  | 'Policy'
  | 'PolicyDomain'
  | 'PolicyRights'
  | 'Preview'
  | 'Primitive'
  | 'QuantumFormat'
  | 'Resource'
  | 'SparseColor'
  | 'Statistic'
  | 'Storage'
  | 'Stretch'
  | 'Style'
  | 'Threshold'
  | 'Tool'
  | 'Type'
  | 'Units'
  | 'Validate'
  | 'VirtualPixel'
  | 'Weight'
  | 'WordBreak'
type WordBreakType = 'Normal' | 'BreakWord'
type ImageType =
  | 'Bilevel'
  | 'ColorSeparation'
  | 'ColorSeparationAlpha'
  | 'ColorSeparationMatte'
  | 'Grayscale'
  | 'GrayscaleAlpha'
  | 'GrayscaleMatte'
  | 'Optimize'
  | 'Palette'
  | 'PaletteBilevelAlpha'
  | 'PaletteBilevelMatte'
  | 'PaletteAlpha'
  | 'PaletteMatte'
  | 'TrueColor'
  | 'TrueColorAlpha'
  | 'TrueColorMatte'
type UnitsType = 'Undefined' | 'PixelsPerInch' | 'PixelsPerCentimeter'
type FontWeightType =
  | 'Thin'
  | 'ExtraLight'
  | 'UltraLight'
  | 'Normal'
  | 'Regular'
  | 'Medium'
  | 'DemiBold'
  | 'SemiBold'
  | 'Bold'
  | 'ExtraBold'
  | 'UltraBold'
  | 'Heavy'
  | 'Black'
type MetricType =
  | 'AE'
  | 'DPC'
  | 'DSSIM'
  | 'Fuzz'
  | 'MAE'
  | 'MEPP'
  | 'MSE'
  | 'NCC'
  | 'PAE'
  | 'PDC'
  | 'PHASE'
  | 'PHASH'
  | 'PSNR'
  | 'RMSE'
  | 'SSIM'
type DrawMethodType = 'point' | 'replace' | 'floodfill' | 'filltoborder' | 'reset'
type NumberOrPercent = number | `${number}%`

export type {
  AlphaType,
  AutoThresholdType,
  ChannelType,
  ColorspaceType,
  ComplexOperatorType,
  ComposeType,
  CompressType,
  DebugType,
  DirectionType,
  DisposeType,
  DistortType,
  DitherType,
  DrawMethodType,
  EndianType,
  EvaluateType,
  FilterType,
  FontWeightType,
  FunctionType,
  GravityType,
  GrayscaleType,
  IlluminantType,
  ImageType,
  IntensityType,
  IntentType,
  InterlaceType,
  InterpolateType,
  LayersType,
  LimitType,
  ListType,
  MetricType,
  MorphologyType,
  NoiseType,
  NumberOrPercent,
  OrientType,
  PreviewType,
  SparseColorMethodType,
  StatisticType,
  StretchType,
  StyleType,
  UnitsType,
  VirtualPixelType,
  WordBreakType,
}
